phraseapp:
  project_id: 8599708ac1bc62a78985748d8fc735cc
  file_format: i18next

  push:
    sources:
    - file: ./test/locales/<locale_name>/app.json

  pull:
    targets:
    - file: ./test/locales/<locale_name>/app.json
      params:
        include_empty_translations: true
